[[main]]
none = "none"

[[main]]
name = "Projects"
pre = "fire"
pageRef = "Projects"
identifier = "cV965taqK8"
weight = 9999


[[main]]
name = "About Me"
pre = "mug-hot"
pageRef = "About Me"
identifier = "kUXVwezcqW"
weight = 9999

[[footer]]
none = "none"
